@startuml
!ifdef AWS_SPRITESPATH
!else
!define AWS_SPRITESPATH https://raw.githubusercontent.com/jballe/plantuml-aws-icons/master/sprites
!endif

!includeurl MS_SPRITESPATH/grayscale/ai_lex.puml
!includeurl MS_SPRITESPATH/grayscale/ai_machinelearning.puml
!includeurl MS_SPRITESPATH/grayscale/ai_polly.puml
!includeurl MS_SPRITESPATH/grayscale/ai_rekognition.puml
!includeurl MS_SPRITESPATH/grayscale/analytics_athena.puml
!includeurl MS_SPRITESPATH/grayscale/analytics_cloudsearch.puml
!includeurl MS_SPRITESPATH/grayscale/analytics_datapipeline.puml
!includeurl MS_SPRITESPATH/grayscale/analytics_emr.puml
!includeurl MS_SPRITESPATH/grayscale/analytics_es.puml
!includeurl MS_SPRITESPATH/grayscale/analytics_glue.puml
!includeurl MS_SPRITESPATH/grayscale/analytics_kinesis.puml
!includeurl MS_SPRITESPATH/grayscale/analytics_quicksight.puml
!includeurl MS_SPRITESPATH/grayscale/analytics_redshift.puml
!includeurl MS_SPRITESPATH/grayscale/applicationservices_apigateway.puml
!includeurl MS_SPRITESPATH/grayscale/applicationservices_appstream.puml
!includeurl MS_SPRITESPATH/grayscale/applicationservices_elastictranscoder.puml
!includeurl MS_SPRITESPATH/grayscale/applicationservices_stepfunction.puml
!includeurl MS_SPRITESPATH/grayscale/businessproductivity_chime.puml
!includeurl MS_SPRITESPATH/grayscale/businessproductivity_workdocs.puml
!includeurl MS_SPRITESPATH/grayscale/businessproductivity_workmail.puml
!includeurl MS_SPRITESPATH/grayscale/compute_batch.puml
!includeurl MS_SPRITESPATH/grayscale/compute_ec2.puml
!includeurl MS_SPRITESPATH/grayscale/compute_ecr.puml
!includeurl MS_SPRITESPATH/grayscale/compute_ecs.puml
!includeurl MS_SPRITESPATH/grayscale/compute_elasticbeanstalk.puml
!includeurl MS_SPRITESPATH/grayscale/compute_elasticloadbalancing.puml
!includeurl MS_SPRITESPATH/grayscale/compute_lambda.puml
!includeurl MS_SPRITESPATH/grayscale/compute_lightsail.puml
!includeurl MS_SPRITESPATH/grayscale/compute_vpc.puml
!includeurl MS_SPRITESPATH/grayscale/contactcenter_connect.puml
!includeurl MS_SPRITESPATH/grayscale/database_dms.puml
!includeurl MS_SPRITESPATH/grayscale/database_dynamodb.puml
!includeurl MS_SPRITESPATH/grayscale/database_dynamodbaccelerator.puml
!includeurl MS_SPRITESPATH/grayscale/database_elasticcache.puml
!includeurl MS_SPRITESPATH/grayscale/database_rds.puml
!includeurl MS_SPRITESPATH/grayscale/database_redshift.puml
!includeurl MS_SPRITESPATH/grayscale/desktopappstreaming_appstream20.puml
!includeurl MS_SPRITESPATH/grayscale/desktopappstreaming_workspaces.puml
!includeurl MS_SPRITESPATH/grayscale/developertools_codebuild.puml
!includeurl MS_SPRITESPATH/grayscale/developertools_codecommit.puml
!includeurl MS_SPRITESPATH/grayscale/developertools_codedeploy.puml
!includeurl MS_SPRITESPATH/grayscale/developertools_codepipeline.puml
!includeurl MS_SPRITESPATH/grayscale/developertools_codestar.puml
!includeurl MS_SPRITESPATH/grayscale/developertools_x_ray.puml
!includeurl MS_SPRITESPATH/grayscale/gamedevelopment_gamelift.puml
!includeurl MS_SPRITESPATH/grayscale/internetofthings_greengrass.puml
!includeurl MS_SPRITESPATH/grayscale/internetofthings_iot.puml
!includeurl MS_SPRITESPATH/grayscale/managementtools_cloudformation.puml
!includeurl MS_SPRITESPATH/grayscale/managementtools_cloudtrail.puml
!includeurl MS_SPRITESPATH/grayscale/managementtools_cloudwatch.puml
!includeurl MS_SPRITESPATH/grayscale/managementtools_config.puml
!includeurl MS_SPRITESPATH/grayscale/managementtools_ec2systemsmanager.puml
!includeurl MS_SPRITESPATH/grayscale/managementtools_managedservices.puml
!includeurl MS_SPRITESPATH/grayscale/managementtools_opsworks.puml
!includeurl MS_SPRITESPATH/grayscale/managementtools_servicecatalog.puml
!includeurl MS_SPRITESPATH/grayscale/managementtools_trustedadvisor.puml
!includeurl MS_SPRITESPATH/grayscale/messaging_pinpoint.puml
!includeurl MS_SPRITESPATH/grayscale/messaging_ses.puml
!includeurl MS_SPRITESPATH/grayscale/messaging_sns.puml
!includeurl MS_SPRITESPATH/grayscale/messaging_sqs.puml
!includeurl MS_SPRITESPATH/grayscale/messaging_swf.puml
!includeurl MS_SPRITESPATH/grayscale/migration_applicationdiscoveryservice.puml
!includeurl MS_SPRITESPATH/grayscale/migration_dms.puml
!includeurl MS_SPRITESPATH/grayscale/migration_migrationhub.puml
!includeurl MS_SPRITESPATH/grayscale/migration_sms.puml
!includeurl MS_SPRITESPATH/grayscale/migration_snowball.puml
!includeurl MS_SPRITESPATH/grayscale/mobileservices_apigateway.puml
!includeurl MS_SPRITESPATH/grayscale/mobileservices_cognito.puml
!includeurl MS_SPRITESPATH/grayscale/mobileservices_devicefarm.puml
!includeurl MS_SPRITESPATH/grayscale/mobileservices_mobileanalytics.puml
!includeurl MS_SPRITESPATH/grayscale/mobileservices_mobilehub.puml
!includeurl MS_SPRITESPATH/grayscale/mobileservices_pinpoint.puml
!includeurl MS_SPRITESPATH/grayscale/networkingcontentdelivery_cloudfront.puml
!includeurl MS_SPRITESPATH/grayscale/networkingcontentdelivery_directconnect.puml
!includeurl MS_SPRITESPATH/grayscale/networkingcontentdelivery_elasticloadbalancing.puml
!includeurl MS_SPRITESPATH/grayscale/networkingcontentdelivery_route53.puml
!includeurl MS_SPRITESPATH/grayscale/networkingcontentdelivery_vpc.puml
!includeurl MS_SPRITESPATH/grayscale/securityidentitycompliance_artifact.puml
!includeurl MS_SPRITESPATH/grayscale/securityidentitycompliance_certificatemanager.puml
!includeurl MS_SPRITESPATH/grayscale/securityidentitycompliance_clouddirectoryservice.puml
!includeurl MS_SPRITESPATH/grayscale/securityidentitycompliance_cloudhsm.puml
!includeurl MS_SPRITESPATH/grayscale/securityidentitycompliance_directoryservice.puml
!includeurl MS_SPRITESPATH/grayscale/securityidentitycompliance_iam.puml
!includeurl MS_SPRITESPATH/grayscale/securityidentitycompliance_inspector.puml
!includeurl MS_SPRITESPATH/grayscale/securityidentitycompliance_kms.puml
!includeurl MS_SPRITESPATH/grayscale/securityidentitycompliance_macie.puml
!includeurl MS_SPRITESPATH/grayscale/securityidentitycompliance_organizations.puml
!includeurl MS_SPRITESPATH/grayscale/securityidentitycompliance_shield.puml
!includeurl MS_SPRITESPATH/grayscale/securityidentitycompliance_waf.puml
!includeurl MS_SPRITESPATH/grayscale/storage_efs.puml
!includeurl MS_SPRITESPATH/grayscale/storage_glacier.puml
!includeurl MS_SPRITESPATH/grayscale/storage_s3.puml
!includeurl MS_SPRITESPATH/grayscale/storage_snowball.puml
!includeurl MS_SPRITESPATH/grayscale/storage_storagegateway.puml
@enduml