@startuml
sprite $cloud [48x48/16] {
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEE95335EE989EEE989EEE989E95358EEEEEEEEEE
EEEEEEEEE30000009500EEE000EE90059000000EEEEEEEEE
EEEEEEEEE003530039008E90009E800900055809EEEEEEEE
EEEEEEEEE99EEE500E003E50008E5009009EEEEEEEEEEEEE
EEEEEEEEEEE989500E500E30805E005E00059EEEEEEEEEEE
EEEEEEEEE80000000E800900800E009E5000089EEEEEEEEE
EEEEEEEE9000330009E00800900800EEE8800009EEEEEEEE
EEEEEEEE500EEE8009E80808E00803EEEEEE8005EEEEEEEE
EEEEEEEE300EEE0009E80005E30008E99EEEE005EEEEEEEE
EEEEEEEE8000800005E90008E8000EE800880009EEEEEEEE
EEEEEEEEE300005808EE300EEE005EE90000005EEEEEEEEE
EEEEEEEEEE958EEE9EEEE9EEEEE9EEEEE9558EEEEEEEEEEE
EEEEEEEEE9EEEEEEEEEEEEEEEEEEEEEEEEEEE999EEEEEEEE
EEEEEEE89EE9EEEEEEEEEEEEEEEEEEEEEE9300003EEEEEEE
EEEEEEE805EEEEEEEEEEEEEEEEEEEEEEEE30080009EEEEEE
EEEEEEEE30059EEEEEEEEEEEEEEEEEEEEEEE55E00EEEEEEE
EEEEEEEEE80000599EEEEEEEEEEEEEEE983000805EEEEEEE
EEEEEEEEEE9300000855899EEE99853000005E809EEEEEEE
EEEEEEEEEEEE980000000000000000000039E905EEEEEEEE
EEEEEEEEEEEEEE95000000000000000059EEE95EEEEEEEEE
EEEEEEEEEEEEEEEEE98580000008589EEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
}

!ifdef AWS_SPRITESPATH
!else
!define MS_SPRITESPATH https://raw.githubusercontent.com/jballe/plantuml-microsoft-icons/master/sprites
!endif

!define AWSIMG_CLOUD_G <img:AWS_SPRITESPATH/general/cloud_gray.png>
!define AWSIMG_CLOUD_B <img:AWS_SPRITESPATH/general/cloud_mono.png>
!define AWSIMG_CLOUD_C <img:AWS_SPRITESPATH/general/cloud.png>
@enduml