@startuml
!ifdef AWS_SPRITESPATH
!else
!define AWS_SPRITESPATH https://raw.githubusercontent.com/jballe/plantuml-aws-icons/master/sprites
!endif

!includeurl MS_SPRITESPATH/networking_content_delivery/cloudfront.puml
!includeurl MS_SPRITESPATH/networking_content_delivery/cloudfront_downloaddistribution.puml
!includeurl MS_SPRITESPATH/networking_content_delivery/cloudfront_edgelocation.puml
!includeurl MS_SPRITESPATH/networking_content_delivery/cloudfront_streamingdistribution.puml
!includeurl MS_SPRITESPATH/networking_content_delivery/directconnect.puml
!includeurl MS_SPRITESPATH/networking_content_delivery/elasticloadbalancing.puml
!includeurl MS_SPRITESPATH/networking_content_delivery/elasticloadbalancing_applicationloadbalancer.puml
!includeurl MS_SPRITESPATH/networking_content_delivery/elasticloadbalancing_classicloadbalancer.puml
!includeurl MS_SPRITESPATH/networking_content_delivery/route53.puml
!includeurl MS_SPRITESPATH/networking_content_delivery/route53_hostedzone.puml
!includeurl MS_SPRITESPATH/networking_content_delivery/route53_routetable.puml
!includeurl MS_SPRITESPATH/networking_content_delivery/vpc.puml
!includeurl MS_SPRITESPATH/networking_content_delivery/vpc_customergateway.puml
!includeurl MS_SPRITESPATH/networking_content_delivery/vpc_elasticnetworkadapter.puml
!includeurl MS_SPRITESPATH/networking_content_delivery/vpc_elasticnetworkinterface.puml
!includeurl MS_SPRITESPATH/networking_content_delivery/vpc_endpoints.puml
!includeurl MS_SPRITESPATH/networking_content_delivery/vpc_flowlogs.puml
!includeurl MS_SPRITESPATH/networking_content_delivery/vpc_internetgateway.puml
!includeurl MS_SPRITESPATH/networking_content_delivery/vpc_networkaccesscontrollist_amazonvpc_networkaccesscontrollist.puml
!includeurl MS_SPRITESPATH/networking_content_delivery/vpc_router.puml
!includeurl MS_SPRITESPATH/networking_content_delivery/vpc_vpcnatgateway.puml
!includeurl MS_SPRITESPATH/networking_content_delivery/vpc_vpcpeering.puml
!includeurl MS_SPRITESPATH/networking_content_delivery/vpc_vpnconnection.puml
!includeurl MS_SPRITESPATH/networking_content_delivery/vpc_vpngateway.puml
@enduml